scanner:
  url: "http://172.22.11.2:30060" # clair
  # url: "http://192.168.6.171:30060"
  type: "clair"
  insecure: false
reporter:
  url: "http://172.22.11.2:32619"
  # url: "http://172.22.11.2:32619"
  type: "elasticsearch"
  insecure: false