scanner:
  clair:
    url: "http://172.22.11.2:30060"
    # url: "http://192.168.6.171:30060"
    insecure: false
  trivy:
    url:
    insecure: false
reporter:
  elasticsearch:
    url: "http://172.22.11.2:32619"
    # url: "http://172.22.11.2:32619"
    insecure: false