apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: azssi/opendistro-kibana
        imagePullPolicy: Always
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana_config.yml
        - name: tls
          mountPath: /usr/share/kibana/config/certs
      volumes:
      - name: config
        configMap:
          name: kibana-config
      - name: tls
        secret:
          secretName: kibana-tls
