name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Send email
      uses: dawidd6/action-send-mail@v3.0.0
      with:
        # SMTP server address
        server_address: mail.tmax.co.kr
        # SMTP server port
        server_port: 995
        # Authenticate as this user to SMTP server
        username: taejune_ahn@tmax.co.kr
        # Authenticate with this password to SMTP server
        password: A3tvqGk2Vs*aur
        # Subject of mail message
        subject: imagescan-api release
        # Recipients mail addresses (separated with comma)
        to: taejune_ahn@tmax.co.kr
        # Full name of mail sender (might be with an email address specified in <>)
        from: taejune_ahn@tmax.co.kr
        # Body of mail message (might be a filename prefixed with file:// to read from)
        body: test message
        # HTML body of mail message (might be a filename prefixed with file:// to read from)
        html_body: # optional
        # Carbon copy recipients (separated with comma)
        cc: # optional
        # Blind carbon copy recipients (separated with comma)
        bcc: # optional
        # An email address that will appear on the Reply-To field
        reply_to: # optional
        # Allow unsigned/invalid certificates
        ignore_cert: # optional
        # Convert body from Markdown to HTML (set content_type input as text/html too)
        convert_markdown: # optional
        # Files that will be added to mail message attachments (separated with comma)
        attachments: # optional
