name: Release

on:
  release:
    types:
      - published

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.0.0
        with:
          # SMTP server address
          server_address: mail.tmax.co.kr
          # SMTP server port
          server_port: 995
          # Authenticate as this user to SMTP server
          username: taejune_ahn@tmax.co.kr
          # Authenticate with this password to SMTP server
          password: A3tvqGk2Vs*aur
          # Subject of mail message
          subject: imagescan-api release
          # Recipients mail addresses (separated with comma)
          to: taejune_ahn@tmax.co.kr
          # Full name of mail sender (might be with an email address specified in <>)
          from: taejune_ahn@tmax.co.kr
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: test message
          # HTML body of mail message (might be a filename prefixed with file:// to read from)
          html_body: # optional