name: Release draft

on:
  pull_request:
    types:
      - closed

jobs:
  update-patch-note:
    if: github.base_ref == 'main' && github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
    - name: Release Drafter
      uses: release-drafter/release-drafter@v5.15.0
      with:
        config-name: release-drafter.yml