name: Release

on:
  release:
    types:
      - published

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.0.0
        env:
          USERNAME: ${{ secrets.SMTP_USERNAME }}
          PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        with:
          server_address: mail.tmax.co.kr
          server_port: 587
          username: $USERNAME
          password: $PASSWORD
          subject: release
          to: taejune_ahn@tmax.co.kr
          from: taejune_ahn@tmax.co.kr
          body: test message